debug: false
showtags: true
templatepath: "./tmpl"
groups:
  -
    name: "aws-single"
    region: "us-east-1"
    puppetmaster: "10.0.0.11"
    tiers:
      -
        name: "innertier"
        instances:
          -
            name: "aws-web01"
            hostname: "aws-web01"
            type: "m3.xlarge"
            zone: "us-east-1c"
            ami: "ami-962f77fe"
            secgroups: "your-secgroup1,your-secgroup2"
            subnet: "your-subnet1"
            keyname: "your-key"
            bootstrap:
              header: "boot-default.tmpl"
              footer: "boot-runpuppet.tmpl"
  -
    name: "aws-double"
    region: "us-east-1"
    puppetmaster: "10.0.0.11"
    tiers:
      -
        name: "innertier"
        instances:
          -
            name: "aws-db01"
            hostname: "aws-db01"
            type: "m3.xlarge"
            zone: "us-east-1c"
            ami: "ami-962f77fe"
            secgroups: "your-secgroup1,your-secgroup2"
            subnet: "your-subnet1"
            keyname: "your-key"
            bootstrap:
              header: "boot-default.tmpl"
              content: "boot-hosts.tmpl"
              footer: "boot-runpuppet.tmpl"
      -
        name: "outertier"
        instances:
          -
            name: "aws-web01"
            hostname: "aws-web01"
            type: "m3.large"
            zone: "us-east-1c"
            ami: "ami-962f77fe"
            secgroups: "your-secgroup1,your-secgroup2"
            subnet: "your-subnet1"
            keyname: "your-key"
            bootstrap:
              header: "boot-default.tmpl"
              content: "boot-hosts-web.tmpl"
              footer: "boot-runpuppet.tmpl"
