debug: false
showtags: true
templatepath: "./tmpl"
groups:
  -
    name: "aws"
    region: "us-east-1"
    puppetmaster: "10.0.0.38"
    tiers:
      -
        name: "innertier"
        instances:
          -
            name: "nitro-test"
            hostname: "nitro-test"
            type: "m3.xlarge"
            zone: "us-east-1c"
            ami: "ami-962f77fe"
            secgroups: "sg-04b4857f,sg-f3a15789"
            subnet: "subnet-e6679fbf"
            keyname: "brian-nitro"
            bootstrap:
              header: "boot-default.tmpl"
              content: "boot-hosts.tmpl"
              footer: "boot-runpuppet.tmpl"
  -
    name: "awstest"
    region: "us-east-1"
    puppetmaster: "10.0.0.38"
    tiers:
      -
        name: "innertier"
        instances:
          -
            name: "nitro-db01"
            hostname: "nitro-db01"
            type: "m3.xlarge"
            zone: "us-east-1c"
            ami: "ami-962f77fe"
            secgroups: "sg-04b4857f,sg-f3a15789"
            subnet: "subnet-e6679fbf"
            keyname: "brian-nitro"
      -
        name: "outertier"
        instances:
          -
            name: "nitro-server01"
            hostname: "nitro-server01"
            type: "m3.large"
            zone: "us-east-1c"
            ami: "ami-962f77fe"
            secgroups: "sg-04b4857f,sg-f3a15789"
            subnet: "subnet-e6679fbf"
            keyname: "brian-nitro"
            bootstrap:
              header: "boot-default.tmpl"
              content: "boot-hosts.tmpl"
              footer: "boot-runpuppet.tmpl"
  -
    name: "awstest2"
    region: "us-east-1"
    puppetmaster: "10.0.0.38"
    tiers:
      -
        name: "tier1"
        instances:
          -
            name: "awstest2_tier1_0"
          -
            name: "awstest2_tier1_1"
          -
            name: "awstest2_tier1_2"
      -
        name: "tier2"
        instances:
          -
            name: "awstest2_tier2_0"
      -
        name: "tier3"
        instances:
          -
            name: "awstest2_tier3_0"
          -
            name: "awstest2_tier3_1"
